replicaCount: 1

image:
  repository: webapp
  tag: latest
  pullPolicy: Never 

service:
  type: NodePort
  port: 5000
  nodePort: 30080

app:
  bgColor: "#e6f7ff"  # Default light blue color
New content
